export type NameEntry = {
  name: string;
  realm: "ancient-high-kingdom" | "forest-realm" | "coastal-elven-state" | "isolated-mountain-enclave" | "fallen-empire";
  nation?: "ancient-high-kingdom" | "forest-realm" | "coastal-elven-state" | "isolated-mountain-enclave" | "fallen-empire";
  culturalOrigin?: "high-elf" | "wood-elf" | "drow" | "ancient-highborn";
  era?: "ancient" | "revival";
  gender?: "masculine" | "feminine" | "neutral";
  context?: "noble" | "common" | "ritual" | "records";
  form?: "everyday" | "formal" | "outsider";
  style?: "elegant" | "nature" | "simple";
  length?: "short" | "medium" | "long";
};

function e(
  name: string,
  realm: NameEntry["realm"],
  culturalOrigin?: NameEntry["culturalOrigin"],
  era?: NameEntry["era"],
  gender?: NameEntry["gender"],
  context?: NameEntry["context"],
  form?: NameEntry["form"],
  style?: NameEntry["style"],
  length?: NameEntry["length"]
): NameEntry {
  return { name, realm, nation: realm, culturalOrigin, era, gender, context, form, style, length };
}

/**
 * IMPORTANT:
 * - This is a fixed, curated inventory (no phonetic/syllable generation).
 * - Delete means delete: no fallback, no mixing, no backups.
 * - Nation is the primary library bucket (60/60/50/50/30 = 250).
 */
export const ELF_NAME_ENTRIES: NameEntry[] = [
  e("Aethenor", "ancient-high-kingdom", undefined, undefined, undefined, undefined, undefined, undefined, undefined),
  e("Caelwyn", "ancient-high-kingdom", undefined, undefined, undefined, undefined, undefined, undefined, undefined),

  e("Elarion", "forest-realm", undefined, undefined, undefined, undefined, undefined, undefined, undefined),
  e("Thalendir", "forest-realm", undefined, undefined, undefined, undefined, undefined, undefined, undefined),

  e("Lythael", "coastal-elven-state", undefined, undefined, undefined, undefined, undefined, undefined, undefined),
  e("Serenith", "coastal-elven-state", undefined, undefined, undefined, undefined, undefined, undefined, undefined),

  e("Virelith", "fallen-empire", undefined, undefined, undefined, undefined, undefined, undefined, undefined),
  e("Maerath", "fallen-empire", undefined, undefined, undefined, undefined, undefined, undefined, undefined),

  e("Aelmir", "isolated-mountain-enclave", undefined, undefined, undefined, undefined, undefined, undefined, undefined),
  e("Erynael", "isolated-mountain-enclave", undefined, undefined, undefined, undefined, undefined, undefined, undefined),

  // =========================================================
  // Ancient High Kingdom (60)  ancient-highborn
  // vibe: courtly, old, high register
  // =========================================================
  e("Aeltharion", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "noble", "formal", "elegant", "long"),
  e("Eloweniel", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "noble", "formal", "elegant", "long"),
  e("Caelendir", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "records", "formal", "elegant", "medium"),
  e("Serelith", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "records", "formal", "elegant", "medium"),
  e("Thalanor", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "noble", "formal", "elegant", "medium"),
  e("Elarienne", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "noble", "formal", "elegant", "long"),
  e("Alarion", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "records", "formal", "elegant", "medium"),
  e("Valenith", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "records", "formal", "elegant", "medium"),
  e("Lorienar", "ancient-high-kingdom", "ancient-highborn", "ancient", "neutral", "noble", "formal", "elegant", "medium"),
  e("Aerendil", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "noble", "formal", "elegant", "medium"),
  e("Elenara", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "noble", "formal", "elegant", "medium"),
  e("Calethir", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "records", "formal", "elegant", "medium"),
  e("Saerina", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "noble", "formal", "elegant", "medium"),
  e("Eryndor", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "records", "formal", "elegant", "medium"),
  e("Elisandre", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "records", "formal", "elegant", "long"),
  e("Aelorian", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "noble", "formal", "elegant", "medium"),
  e("Liraelith", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "ritual", "formal", "elegant", "long"),
  e("Thalerion", "ancient-high-kingdom", "ancient-highborn", "ancient", "neutral", "records", "formal", "elegant", "medium"),
  e("Elandor", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "noble", "formal", "elegant", "medium"),
  e("Aralith", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "records", "formal", "elegant", "medium"),
  e("Saelion", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "noble", "formal", "elegant", "medium"),
  e("Eleniel", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "noble", "formal", "elegant", "medium"),
  e("Calanor", "ancient-high-kingdom", "ancient-highborn", "ancient", "neutral", "records", "formal", "elegant", "medium"),
  e("Aethlorin", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "records", "formal", "elegant", "long"),
  e("Serenia", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "common", "everyday", "elegant", "medium"),
  e("Elirion", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "records", "formal", "elegant", "medium"),
  e("Aelira", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "noble", "formal", "elegant", "short"),
  e("Loraniel", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "records", "formal", "elegant", "medium"),
  e("Thalendir", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "noble", "formal", "elegant", "long"),
  e("Eryssae", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "ritual", "formal", "elegant", "medium"),
  e("Calerion", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "records", "formal", "elegant", "medium"),
  e("Saelith", "ancient-high-kingdom", "ancient-highborn", "ancient", "neutral", "records", "formal", "elegant", "medium"),
  e("Elarion", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "noble", "formal", "elegant", "medium"),
  e("Valeria", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "common", "everyday", "elegant", "medium"),
  e("Aelwyn", "ancient-high-kingdom", "ancient-highborn", "ancient", "neutral", "noble", "formal", "elegant", "short"),
  e("Elenor", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "common", "everyday", "elegant", "short"),
  e("Serelor", "ancient-high-kingdom", "ancient-highborn", "ancient", "neutral", "records", "formal", "elegant", "medium"),
  e("Caelith", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "records", "formal", "elegant", "medium"),
  e("Thalor", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "common", "everyday", "simple", "short"),
  e("Lirion", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "common", "everyday", "elegant", "medium"),
  e("Eryna", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "common", "everyday", "elegant", "short"),
  e("Calith", "ancient-high-kingdom", "ancient-highborn", "ancient", "neutral", "common", "everyday", "simple", "short"),
  e("Aelthir", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "records", "formal", "elegant", "medium"),
  e("Elisara", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "noble", "formal", "elegant", "medium"),
  e("Saerinor", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "ritual", "formal", "elegant", "long"),
  e("Elandria", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "ritual", "formal", "elegant", "long"),
  e("Calenor", "ancient-high-kingdom", "ancient-highborn", "ancient", "neutral", "records", "formal", "elegant", "medium"),
  e("Thalienne", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "noble", "formal", "elegant", "long"),
  e("Aelorin", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "noble", "formal", "elegant", "medium"),
  e("Elenwyn", "ancient-high-kingdom", "ancient-highborn", "ancient", "neutral", "common", "everyday", "elegant", "medium"),
  e("Serethir", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "records", "formal", "elegant", "medium"),
  e("Caeriel", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "records", "formal", "elegant", "medium"),
  e("Thalara", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "common", "everyday", "elegant", "medium"),
  e("Lorienel", "ancient-high-kingdom", "ancient-highborn", "ancient", "neutral", "noble", "formal", "elegant", "long"),
  e("Eryndiel", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "ritual", "formal", "elegant", "long"),
  e("Calessia", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "records", "formal", "elegant", "long"),
  e("Saelor", "ancient-high-kingdom", "ancient-highborn", "ancient", "neutral", "common", "everyday", "simple", "short"),
  e("Elarith", "ancient-high-kingdom", "ancient-highborn", "ancient", "feminine", "records", "formal", "elegant", "medium"),
  e("Valendor", "ancient-high-kingdom", "ancient-highborn", "ancient", "masculine", "records", "formal", "elegant", "medium"),
  e("Aelion", "ancient-high-kingdom", "ancient-highborn", "ancient", "neutral", "common", "outsider", "simple", "short"),

  // =========================================================
  // Forest Realm (60)  wood-elf
  // vibe: soft, organic, ranger-friendly
  // =========================================================
  e("Sylwen", "forest-realm", "wood-elf", "revival", "feminine", "common", "everyday", "nature", "short"),
  e("Faelar", "forest-realm", "wood-elf", "revival", "masculine", "common", "everyday", "nature", "medium"),
  e("Rilwyn", "forest-realm", "wood-elf", "revival", "neutral", "common", "everyday", "nature", "short"),
  e("Lethiel", "forest-realm", "wood-elf", "revival", "feminine", "ritual", "formal", "nature", "medium"),
  e("Myrion", "forest-realm", "wood-elf", "revival", "masculine", "common", "everyday", "nature", "medium"),
  e("Sylira", "forest-realm", "wood-elf", "revival", "feminine", "common", "everyday", "nature", "medium"),
  e("Fennor", "forest-realm", "wood-elf", "revival", "masculine", "common", "everyday", "nature", "medium"),
  e("Risana", "forest-realm", "wood-elf", "revival", "feminine", "common", "everyday", "nature", "medium"),
  e("Theryn", "forest-realm", "wood-elf", "revival", "neutral", "common", "everyday", "nature", "medium"),
  e("Sylanor", "forest-realm", "wood-elf", "revival", "masculine", "common", "everyday", "nature", "medium"),
  e("Faenith", "forest-realm", "wood-elf", "revival", "feminine", "ritual", "formal", "nature", "medium"),
  e("Rilion", "forest-realm", "wood-elf", "revival", "masculine", "common", "outsider", "simple", "medium"),
  e("Liora", "forest-realm", "wood-elf", "revival", "feminine", "common", "everyday", "nature", "short"),
  e("Meren", "forest-realm", "wood-elf", "revival", "neutral", "common", "everyday", "simple", "short"),
  e("Sylthir", "forest-realm", "wood-elf", "revival", "masculine", "common", "everyday", "nature", "medium"),
  e("Faewyn", "forest-realm", "wood-elf", "revival", "neutral", "common", "everyday", "nature", "medium"),
  e("Rilen", "forest-realm", "wood-elf", "revival", "masculine", "common", "everyday", "simple", "short"),
  e("Lethira", "forest-realm", "wood-elf", "revival", "feminine", "common", "everyday", "nature", "medium"),
  e("Myrwen", "forest-realm", "wood-elf", "revival", "feminine", "common", "everyday", "nature", "medium"),
  e("Fenna", "forest-realm", "wood-elf", "revival", "feminine", "common", "everyday", "nature", "short"),
  e("Risael", "forest-realm", "wood-elf", "revival", "neutral", "ritual", "formal", "nature", "medium"),
  e("Sylamir", "forest-realm", "wood-elf", "revival", "masculine", "common", "everyday", "nature", "medium"),
  e("Faenor", "forest-realm", "wood-elf", "revival", "masculine", "common", "everyday", "nature", "medium"),
  e("Lirin", "forest-realm", "wood-elf", "revival", "neutral", "common", "everyday", "simple", "short"),
  e("Myrla", "forest-realm", "wood-elf", "revival", "feminine", "common", "everyday", "simple", "short"),
  e("Fenthiel", "forest-realm", "wood-elf", "revival", "masculine", "ritual", "formal", "nature", "long"),
  e("Rilara", "forest-realm", "wood-elf", "revival", "feminine", "common", "everyday", "nature", "medium"),
  e("Sylena", "forest-realm", "wood-elf", "revival", "feminine", "common", "everyday", "nature", "medium"),
  e("Faelith", "forest-realm", "wood-elf", "revival", "neutral", "ritual", "formal", "nature", "medium"),
  e("Lethor", "forest-realm", "wood-elf", "revival", "masculine", "common", "everyday", "simple", "short"),
  e("Myrith", "forest-realm", "wood-elf", "revival", "neutral", "common", "everyday", "nature", "short"),
  e("Fenniel", "forest-realm", "wood-elf", "revival", "feminine", "common", "everyday", "nature", "medium"),
  e("Risaen", "forest-realm", "wood-elf", "revival", "neutral", "common", "everyday", "nature", "medium"),
  e("Sylorin", "forest-realm", "wood-elf", "revival", "masculine", "common", "everyday", "nature", "medium"),
  e("Faenya", "forest-realm", "wood-elf", "revival", "feminine", "ritual", "formal", "nature", "medium"),
  e("Lethen", "forest-realm", "wood-elf", "revival", "neutral", "common", "everyday", "simple", "short"),
  e("Myrionel", "forest-realm", "wood-elf", "revival", "masculine", "common", "everyday", "nature", "long"),
  e("Fennoril", "forest-realm", "wood-elf", "revival", "masculine", "common", "outsider", "nature", "long"),
  e("Rilith", "forest-realm", "wood-elf", "revival", "neutral", "common", "everyday", "nature", "short"),
  e("Sylara", "forest-realm", "wood-elf", "revival", "feminine", "common", "everyday", "nature", "medium"),
  e("Faelor", "forest-realm", "wood-elf", "revival", "masculine", "common", "everyday", "nature", "medium"),
  e("Liorael", "forest-realm", "wood-elf", "revival", "feminine", "ritual", "formal", "nature", "long"),
  e("Merenyl", "forest-realm", "wood-elf", "revival", "neutral", "common", "everyday", "nature", "medium"),
  e("Fennwyn", "forest-realm", "wood-elf", "revival", "neutral", "common", "everyday", "nature", "medium"),
  e("Risanael", "forest-realm", "wood-elf", "revival", "feminine", "records", "formal", "nature", "long"),
  e("Sylthiel", "forest-realm", "wood-elf", "revival", "masculine", "ritual", "formal", "nature", "long"),
  e("Faeniel", "forest-realm", "wood-elf", "revival", "feminine", "common", "everyday", "nature", "medium"),
  e("Lethwyn", "forest-realm", "wood-elf", "revival", "neutral", "common", "everyday", "nature", "medium"),
  e("Myranor", "forest-realm", "wood-elf", "revival", "masculine", "common", "everyday", "nature", "medium"),
  e("Fenael", "forest-realm", "wood-elf", "revival", "neutral", "ritual", "formal", "nature", "medium"),
  e("Rilenna", "forest-realm", "wood-elf", "revival", "feminine", "common", "everyday", "simple", "medium"),
  e("Syliren", "forest-realm", "wood-elf", "revival", "neutral", "common", "everyday", "nature", "medium"),
  e("Faethir", "forest-realm", "wood-elf", "revival", "masculine", "common", "everyday", "nature", "medium"),
  e("Lioren", "forest-realm", "wood-elf", "revival", "neutral", "common", "everyday", "simple", "short"),
  e("Myris", "forest-realm", "wood-elf", "revival", "neutral", "common", "everyday", "simple", "short"),
  e("Fennara", "forest-realm", "wood-elf", "revival", "feminine", "common", "everyday", "nature", "medium"),
  e("Rilamir", "forest-realm", "wood-elf", "revival", "masculine", "common", "everyday", "nature", "medium"),
  e("Sylmaer", "forest-realm", "wood-elf", "revival", "neutral", "records", "formal", "nature", "medium"),
  e("Faenithiel", "forest-realm", "wood-elf", "revival", "feminine", "ritual", "formal", "nature", "long"),
  e("Lethirion", "forest-realm", "wood-elf", "revival", "masculine", "records", "formal", "nature", "long"),

  // =========================================================
  // Coastal Elven State (50)  high-elf
  // vibe: bright, maritime, diplomatic
  // =========================================================
  e("Aerelion", "coastal-elven-state", "high-elf", "revival", "masculine", "noble", "formal", "elegant", "medium"),
  e("Eiranel", "coastal-elven-state", "high-elf", "revival", "feminine", "noble", "formal", "elegant", "medium"),
  e("Caladir", "coastal-elven-state", "high-elf", "revival", "masculine", "records", "formal", "elegant", "medium"),
  e("Saelina", "coastal-elven-state", "high-elf", "revival", "feminine", "common", "everyday", "elegant", "medium"),
  e("Aeralith", "coastal-elven-state", "high-elf", "revival", "neutral", "noble", "formal", "elegant", "medium"),
  e("Eirion", "coastal-elven-state", "high-elf", "revival", "masculine", "common", "everyday", "elegant", "short"),
  e("Calenya", "coastal-elven-state", "high-elf", "revival", "feminine", "records", "formal", "elegant", "medium"),
  e("Vaelorin", "coastal-elven-state", "high-elf", "revival", "masculine", "noble", "formal", "elegant", "medium"),
  e("Aerienna", "coastal-elven-state", "high-elf", "revival", "feminine", "noble", "formal", "elegant", "long"),
  e("Eirana", "coastal-elven-state", "high-elf", "revival", "feminine", "common", "everyday", "elegant", "short"),
  e("Calerith", "coastal-elven-state", "high-elf", "revival", "neutral", "records", "formal", "elegant", "medium"),
  e("Saelorin", "coastal-elven-state", "high-elf", "revival", "masculine", "records", "formal", "elegant", "long"),
  e("Aerendria", "coastal-elven-state", "high-elf", "revival", "feminine", "ritual", "formal", "elegant", "long"),
  e("Eirathiel", "coastal-elven-state", "high-elf", "revival", "neutral", "records", "formal", "elegant", "long"),
  e("Calanor", "coastal-elven-state", "high-elf", "revival", "masculine", "common", "everyday", "simple", "medium"),
  e("Vaelira", "coastal-elven-state", "high-elf", "revival", "feminine", "common", "everyday", "elegant", "short"),
  e("Aeralen", "coastal-elven-state", "high-elf", "revival", "neutral", "common", "everyday", "elegant", "medium"),
  e("Eirendor", "coastal-elven-state", "high-elf", "revival", "masculine", "records", "formal", "elegant", "medium"),
  e("Calessa", "coastal-elven-state", "high-elf", "revival", "feminine", "records", "formal", "elegant", "medium"),
  e("Saerel", "coastal-elven-state", "high-elf", "revival", "neutral", "common", "everyday", "simple", "short"),
  e("Aeryn", "coastal-elven-state", "high-elf", "revival", "neutral", "common", "everyday", "simple", "short"),
  e("Eiriel", "coastal-elven-state", "high-elf", "revival", "feminine", "common", "everyday", "elegant", "short"),
  e("Calethir", "coastal-elven-state", "high-elf", "revival", "masculine", "records", "formal", "elegant", "medium"),
  e("Vaelion", "coastal-elven-state", "high-elf", "revival", "masculine", "noble", "formal", "elegant", "medium"),
  e("Aerilith", "coastal-elven-state", "high-elf", "revival", "feminine", "records", "formal", "elegant", "medium"),
  e("Eirith", "coastal-elven-state", "high-elf", "revival", "neutral", "common", "everyday", "simple", "short"),
  e("Calenor", "coastal-elven-state", "high-elf", "revival", "neutral", "records", "formal", "elegant", "medium"),
  e("Saerinae", "coastal-elven-state", "high-elf", "revival", "feminine", "ritual", "formal", "elegant", "long"),
  e("Aerendil", "coastal-elven-state", "high-elf", "revival", "masculine", "noble", "formal", "elegant", "medium"),
  e("Eiranor", "coastal-elven-state", "high-elf", "revival", "masculine", "common", "everyday", "elegant", "medium"),
  e("Calira", "coastal-elven-state", "high-elf", "revival", "feminine", "common", "everyday", "elegant", "short"),
  e("Vaelith", "coastal-elven-state", "high-elf", "revival", "neutral", "records", "formal", "elegant", "medium"),
  e("Aerion", "coastal-elven-state", "high-elf", "revival", "masculine", "common", "outsider", "simple", "short"),
  e("Eiravyn", "coastal-elven-state", "high-elf", "revival", "feminine", "common", "outsider", "simple", "medium"),
  e("Calenith", "coastal-elven-state", "high-elf", "revival", "neutral", "records", "formal", "elegant", "medium"),
  e("Saelith", "coastal-elven-state", "high-elf", "revival", "feminine", "records", "formal", "elegant", "medium"),
  e("Aerendria", "coastal-elven-state", "high-elf", "revival", "feminine", "noble", "formal", "elegant", "long"),
  e("Eirathor", "coastal-elven-state", "high-elf", "revival", "masculine", "records", "formal", "elegant", "medium"),
  e("Calerion", "coastal-elven-state", "high-elf", "revival", "masculine", "records", "formal", "elegant", "medium"),
  e("Vaeloria", "coastal-elven-state", "high-elf", "revival", "feminine", "noble", "formal", "elegant", "long"),
  e("Aerelithiel", "coastal-elven-state", "high-elf", "revival", "neutral", "records", "formal", "elegant", "long"),
  e("Eiraniel", "coastal-elven-state", "high-elf", "revival", "feminine", "records", "formal", "elegant", "medium"),
  e("Calion", "coastal-elven-state", "high-elf", "revival", "neutral", "common", "everyday", "simple", "short"),
  e("Saerendor", "coastal-elven-state", "high-elf", "revival", "masculine", "records", "formal", "elegant", "long"),
  e("Aeraloria", "coastal-elven-state", "high-elf", "revival", "feminine", "ritual", "formal", "elegant", "long"),
  e("Eiralen", "coastal-elven-state", "high-elf", "revival", "neutral", "common", "everyday", "elegant", "medium"),
  e("Vaelorien", "coastal-elven-state", "high-elf", "revival", "neutral", "noble", "formal", "elegant", "long"),
  e("Calethia", "coastal-elven-state", "high-elf", "revival", "feminine", "records", "formal", "elegant", "medium"),
  e("Aerendir", "coastal-elven-state", "high-elf", "revival", "masculine", "records", "formal", "elegant", "medium"),
  e("Saeliora", "coastal-elven-state", "high-elf", "revival", "feminine", "noble", "formal", "elegant", "long"),

  // =========================================================
  // Fallen Empire (50)  drow
  // vibe: sharp, shadowed, imperial ruins
  // =========================================================
  e("Draveth", "fallen-empire", "drow", "ancient", "masculine", "records", "formal", "elegant", "medium"),
  e("Zirnaeth", "fallen-empire", "drow", "ancient", "feminine", "noble", "formal", "elegant", "medium"),
  e("Vesryn", "fallen-empire", "drow", "ancient", "neutral", "common", "everyday", "simple", "medium"),
  e("Thariz", "fallen-empire", "drow", "ancient", "masculine", "common", "outsider", "simple", "short"),
  e("Drisara", "fallen-empire", "drow", "ancient", "feminine", "common", "everyday", "elegant", "medium"),
  e("Zireth", "fallen-empire", "drow", "ancient", "neutral", "records", "formal", "elegant", "short"),
  e("Varyn", "fallen-empire", "drow", "ancient", "masculine", "common", "everyday", "simple", "short"),
  e("Thalrys", "fallen-empire", "drow", "ancient", "neutral", "ritual", "formal", "elegant", "medium"),
  e("Dravira", "fallen-empire", "drow", "ancient", "feminine", "noble", "formal", "elegant", "medium"),
  e("Zirveth", "fallen-empire", "drow", "ancient", "masculine", "records", "formal", "elegant", "medium"),
  e("Veslith", "fallen-empire", "drow", "ancient", "feminine", "records", "formal", "elegant", "medium"),
  e("Thariel", "fallen-empire", "drow", "ancient", "neutral", "records", "formal", "elegant", "medium"),
  e("Driseth", "fallen-empire", "drow", "ancient", "masculine", "common", "everyday", "simple", "medium"),
  e("Ziraesha", "fallen-empire", "drow", "ancient", "feminine", "ritual", "formal", "elegant", "long"),
  e("Varynna", "fallen-empire", "drow", "ancient", "feminine", "common", "everyday", "simple", "medium"),
  e("Thalorin", "fallen-empire", "drow", "ancient", "masculine", "records", "formal", "elegant", "medium"),
  e("Draventh", "fallen-empire", "drow", "ancient", "neutral", "records", "formal", "elegant", "medium"),
  e("Zirielle", "fallen-empire", "drow", "ancient", "feminine", "noble", "formal", "elegant", "long"),
  e("Vesrion", "fallen-empire", "drow", "ancient", "masculine", "records", "formal", "elegant", "medium"),
  e("Tharissa", "fallen-empire", "drow", "ancient", "feminine", "common", "everyday", "elegant", "medium"),
  e("Drisniel", "fallen-empire", "drow", "ancient", "neutral", "records", "formal", "elegant", "medium"),
  e("Zirath", "fallen-empire", "drow", "ancient", "masculine", "common", "outsider", "simple", "short"),
  e("Varyneth", "fallen-empire", "drow", "ancient", "neutral", "records", "formal", "elegant", "medium"),
  e("Thalvyr", "fallen-empire", "drow", "ancient", "masculine", "common", "everyday", "simple", "medium"),
  e("Dravryn", "fallen-empire", "drow", "ancient", "masculine", "common", "everyday", "simple", "medium"),
  e("Zirael", "fallen-empire", "drow", "ancient", "neutral", "ritual", "formal", "elegant", "medium"),
  e("Vesnara", "fallen-empire", "drow", "ancient", "feminine", "common", "everyday", "simple", "medium"),
  e("Tharenth", "fallen-empire", "drow", "ancient", "masculine", "records", "formal", "elegant", "medium"),
  e("Driselle", "fallen-empire", "drow", "ancient", "feminine", "records", "formal", "elegant", "medium"),
  e("Zirniel", "fallen-empire", "drow", "ancient", "neutral", "records", "formal", "elegant", "medium"),
  e("Varyssa", "fallen-empire", "drow", "ancient", "feminine", "common", "everyday", "elegant", "medium"),
  e("Thalreth", "fallen-empire", "drow", "ancient", "neutral", "ritual", "formal", "elegant", "medium"),
  e("Dravisa", "fallen-empire", "drow", "ancient", "feminine", "common", "everyday", "simple", "medium"),
  e("Zirvyr", "fallen-empire", "drow", "ancient", "masculine", "common", "everyday", "simple", "medium"),
  e("Vesriel", "fallen-empire", "drow", "ancient", "neutral", "records", "formal", "elegant", "medium"),
  e("Tharilyn", "fallen-empire", "drow", "ancient", "feminine", "records", "formal", "elegant", "medium"),
  e("Drisareth", "fallen-empire", "drow", "ancient", "neutral", "records", "formal", "elegant", "long"),
  e("Zirona", "fallen-empire", "drow", "ancient", "feminine", "common", "everyday", "simple", "short"),
  e("Varyniel", "fallen-empire", "drow", "ancient", "neutral", "records", "formal", "elegant", "medium"),
  e("Thalrion", "fallen-empire", "drow", "ancient", "masculine", "records", "formal", "elegant", "medium"),
  e("Draviel", "fallen-empire", "drow", "ancient", "masculine", "records", "formal", "elegant", "medium"),
  e("Zirathiel", "fallen-empire", "drow", "ancient", "neutral", "ritual", "formal", "elegant", "long"),
  e("Veslira", "fallen-empire", "drow", "ancient", "feminine", "common", "everyday", "elegant", "medium"),
  e("Tharveth", "fallen-empire", "drow", "ancient", "masculine", "records", "formal", "elegant", "medium"),
  e("Drisvyr", "fallen-empire", "drow", "ancient", "neutral", "common", "everyday", "simple", "medium"),
  e("Zirethra", "fallen-empire", "drow", "ancient", "feminine", "records", "formal", "elegant", "medium"),
  e("Varynlor", "fallen-empire", "drow", "ancient", "masculine", "records", "formal", "elegant", "medium"),
  e("Thalessa", "fallen-empire", "drow", "ancient", "feminine", "common", "everyday", "elegant", "medium"),
  e("Dravorn", "fallen-empire", "drow", "ancient", "masculine", "common", "outsider", "simple", "short"),
  e("Zirsel", "fallen-empire", "drow", "ancient", "neutral", "common", "outsider", "simple", "short"),

  // =========================================================
  // Isolated Mountain Enclave (30)  high-elf (austere, carved-stone tradition)
  // vibe: crisp, restrained, formal-leaning
  // =========================================================
  e("Aethren", "isolated-mountain-enclave", "high-elf", "revival", "neutral", "common", "everyday", "simple", "short"),
  e("Caelthir", "isolated-mountain-enclave", "high-elf", "revival", "masculine", "records", "formal", "elegant", "medium"),
  e("Elenmir", "isolated-mountain-enclave", "high-elf", "revival", "neutral", "records", "formal", "elegant", "medium"),
  e("Thalren", "isolated-mountain-enclave", "high-elf", "revival", "masculine", "common", "everyday", "simple", "short"),
  e("Aelthra", "isolated-mountain-enclave", "high-elf", "revival", "feminine", "records", "formal", "elegant", "medium"),
  e("Calenreth", "isolated-mountain-enclave", "high-elf", "revival", "neutral", "records", "formal", "elegant", "long"),
  e("Eryndir", "isolated-mountain-enclave", "high-elf", "revival", "masculine", "records", "formal", "elegant", "medium"),
  e("Serenith", "isolated-mountain-enclave", "high-elf", "revival", "feminine", "records", "formal", "elegant", "medium"),
  e("Aethlor", "isolated-mountain-enclave", "high-elf", "revival", "neutral", "common", "everyday", "simple", "short"),
  e("Caelorin", "isolated-mountain-enclave", "high-elf", "revival", "masculine", "noble", "formal", "elegant", "medium"),
  e("Elenreth", "isolated-mountain-enclave", "high-elf", "revival", "neutral", "records", "formal", "elegant", "medium"),
  e("Thalendir", "isolated-mountain-enclave", "high-elf", "revival", "masculine", "records", "formal", "elegant", "long"),
  e("Aelmir", "isolated-mountain-enclave", "high-elf", "revival", "neutral", "common", "everyday", "simple", "short"),
  e("Caleth", "isolated-mountain-enclave", "high-elf", "revival", "masculine", "common", "everyday", "simple", "short"),
  e("Erynael", "isolated-mountain-enclave", "high-elf", "revival", "feminine", "ritual", "formal", "elegant", "medium"),
  e("Serelor", "isolated-mountain-enclave", "high-elf", "revival", "neutral", "records", "formal", "elegant", "medium"),
  e("Aethrion", "isolated-mountain-enclave", "high-elf", "revival", "masculine", "records", "formal", "elegant", "medium"),
  e("Caelira", "isolated-mountain-enclave", "high-elf", "revival", "feminine", "common", "everyday", "elegant", "short"),
  e("Elenara", "isolated-mountain-enclave", "high-elf", "revival", "feminine", "records", "formal", "elegant", "medium"),
  e("Thalorim", "isolated-mountain-enclave", "high-elf", "revival", "neutral", "records", "formal", "elegant", "medium"),
  e("Aelreth", "isolated-mountain-enclave", "high-elf", "revival", "neutral", "records", "formal", "elegant", "medium"),
  e("Caelwyn", "isolated-mountain-enclave", "high-elf", "revival", "neutral", "common", "everyday", "simple", "medium"),
  e("Eryndel", "isolated-mountain-enclave", "high-elf", "revival", "masculine", "records", "formal", "elegant", "medium"),
  e("Serenya", "isolated-mountain-enclave", "high-elf", "revival", "feminine", "common", "everyday", "elegant", "medium"),
  e("Aethlith", "isolated-mountain-enclave", "high-elf", "revival", "feminine", "records", "formal", "elegant", "medium"),
  e("Calenor", "isolated-mountain-enclave", "high-elf", "revival", "neutral", "records", "formal", "elegant", "medium"),
  e("Elenor", "isolated-mountain-enclave", "high-elf", "revival", "masculine", "common", "everyday", "simple", "short"),
  e("Thalwyn", "isolated-mountain-enclave", "high-elf", "revival", "neutral", "common", "everyday", "simple", "medium"),
  e("Aelthiel", "isolated-mountain-enclave", "high-elf", "revival", "neutral", "records", "formal", "elegant", "long"),
  e("Aethenor", "isolated-mountain-enclave", "high-elf", "revival", "neutral", "records", "formal", "elegant", "medium"),
];
